version: '3'
services:

  python:
    container_name: mol_${JSON_FILE_TRUNC}
    image: message_on_live:twitch
    build:
      context: ./
    volumes:
      - ../logs:/app/logs
      - ../configurations/${JSON_FILE}:/app/data.json:ro
    env_file:
      - .env
    environment:
      - APP_ID=${APP_ID}
      - USER_TOKEN=${USER_TOKEN}
      - JSON_FILE=${JSON_FILE}
