version: '3'
services:

  python:
    build:
      context: ./
    volumes:
      - ../channels:/app/channels
    env_file:
      - .env
    environment:
      - APP_ID=${APP_ID}
      - USER_TOKEN=${USER_TOKEN}